spring:
  datasource:
    username: root
    password: sharemedata
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://129.204.255.70:3306/shareme?useSSL=false&useUnicode=true&characterEncoding=UTF-8

constconfig:
  error-message:
    0: loginError