package com.ammy.shareme.server.dao.model;

import java.io.Serializable;
import java.util.Date;

public class MomentInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moment_info.moment_id
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    private Integer momentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moment_info.user_id
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moment_info.forward_flag
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    private Integer forwardFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moment_info.base_url
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    private String baseUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moment_info.create_time
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moment_info.modify_time
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moment_info.type
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moment_info.text
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moment_info.like
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    private Integer like;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moment_info.comment
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    private Integer comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moment_info.forward
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    private Integer forward;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moment_info.url
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moment_info.recommend_flag
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    private Integer recommendFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table moment_info
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moment_info.moment_id
     *
     * @return the value of moment_info.moment_id
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    public Integer getMomentId() {
        return momentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moment_info.moment_id
     *
     * @param momentId the value for moment_info.moment_id
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    public void setMomentId(Integer momentId) {
        this.momentId = momentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moment_info.user_id
     *
     * @return the value of moment_info.user_id
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moment_info.user_id
     *
     * @param userId the value for moment_info.user_id
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moment_info.forward_flag
     *
     * @return the value of moment_info.forward_flag
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    public Integer getForwardFlag() {
        return forwardFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moment_info.forward_flag
     *
     * @param forwardFlag the value for moment_info.forward_flag
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    public void setForwardFlag(Integer forwardFlag) {
        this.forwardFlag = forwardFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moment_info.base_url
     *
     * @return the value of moment_info.base_url
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    public String getBaseUrl() {
        return baseUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moment_info.base_url
     *
     * @param baseUrl the value for moment_info.base_url
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    public void setBaseUrl(String baseUrl) {
        this.baseUrl = baseUrl == null ? null : baseUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moment_info.create_time
     *
     * @return the value of moment_info.create_time
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moment_info.create_time
     *
     * @param createTime the value for moment_info.create_time
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moment_info.modify_time
     *
     * @return the value of moment_info.modify_time
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moment_info.modify_time
     *
     * @param modifyTime the value for moment_info.modify_time
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moment_info.type
     *
     * @return the value of moment_info.type
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moment_info.type
     *
     * @param type the value for moment_info.type
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moment_info.text
     *
     * @return the value of moment_info.text
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moment_info.text
     *
     * @param text the value for moment_info.text
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moment_info.like
     *
     * @return the value of moment_info.like
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    public Integer getLike() {
        return like;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moment_info.like
     *
     * @param like the value for moment_info.like
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    public void setLike(Integer like) {
        this.like = like;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moment_info.comment
     *
     * @return the value of moment_info.comment
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    public Integer getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moment_info.comment
     *
     * @param comment the value for moment_info.comment
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    public void setComment(Integer comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moment_info.forward
     *
     * @return the value of moment_info.forward
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    public Integer getForward() {
        return forward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moment_info.forward
     *
     * @param forward the value for moment_info.forward
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    public void setForward(Integer forward) {
        this.forward = forward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moment_info.url
     *
     * @return the value of moment_info.url
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moment_info.url
     *
     * @param url the value for moment_info.url
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moment_info.recommend_flag
     *
     * @return the value of moment_info.recommend_flag
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    public Integer getRecommendFlag() {
        return recommendFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moment_info.recommend_flag
     *
     * @param recommendFlag the value for moment_info.recommend_flag
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    public void setRecommendFlag(Integer recommendFlag) {
        this.recommendFlag = recommendFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moment_info
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MomentInfo other = (MomentInfo) that;
        return (this.getMomentId() == null ? other.getMomentId() == null : this.getMomentId().equals(other.getMomentId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getForwardFlag() == null ? other.getForwardFlag() == null : this.getForwardFlag().equals(other.getForwardFlag()))
            && (this.getBaseUrl() == null ? other.getBaseUrl() == null : this.getBaseUrl().equals(other.getBaseUrl()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getText() == null ? other.getText() == null : this.getText().equals(other.getText()))
            && (this.getLike() == null ? other.getLike() == null : this.getLike().equals(other.getLike()))
            && (this.getComment() == null ? other.getComment() == null : this.getComment().equals(other.getComment()))
            && (this.getForward() == null ? other.getForward() == null : this.getForward().equals(other.getForward()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getRecommendFlag() == null ? other.getRecommendFlag() == null : this.getRecommendFlag().equals(other.getRecommendFlag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moment_info
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMomentId() == null) ? 0 : getMomentId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getForwardFlag() == null) ? 0 : getForwardFlag().hashCode());
        result = prime * result + ((getBaseUrl() == null) ? 0 : getBaseUrl().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getText() == null) ? 0 : getText().hashCode());
        result = prime * result + ((getLike() == null) ? 0 : getLike().hashCode());
        result = prime * result + ((getComment() == null) ? 0 : getComment().hashCode());
        result = prime * result + ((getForward() == null) ? 0 : getForward().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getRecommendFlag() == null) ? 0 : getRecommendFlag().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moment_info
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", momentId=").append(momentId);
        sb.append(", userId=").append(userId);
        sb.append(", forwardFlag=").append(forwardFlag);
        sb.append(", baseUrl=").append(baseUrl);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", type=").append(type);
        sb.append(", text=").append(text);
        sb.append(", like=").append(like);
        sb.append(", comment=").append(comment);
        sb.append(", forward=").append(forward);
        sb.append(", url=").append(url);
        sb.append(", recommendFlag=").append(recommendFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}