package com.ammy.shareme.server.dao.model;

import java.io.Serializable;
import java.util.Date;

public class RelationshipInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relationship_info.focus_id
     *
     * @mbggenerated Tue Jul 09 18:50:38 CST 2019
     */
    private Integer focusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relationship_info.follow_user_id
     *
     * @mbggenerated Tue Jul 09 18:50:38 CST 2019
     */
    private Integer followUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relationship_info.focus_user_id
     *
     * @mbggenerated Tue Jul 09 18:50:38 CST 2019
     */
    private Integer focusUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relationship_info.operation_flag
     *
     * @mbggenerated Tue Jul 09 18:50:38 CST 2019
     */
    private Integer operationFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relationship_info.cancel_flag
     *
     * @mbggenerated Tue Jul 09 18:50:38 CST 2019
     */
    private Integer cancelFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relationship_info.create_time
     *
     * @mbggenerated Tue Jul 09 18:50:38 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relationship_info.modify_time
     *
     * @mbggenerated Tue Jul 09 18:50:38 CST 2019
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table relationship_info
     *
     * @mbggenerated Tue Jul 09 18:50:38 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relationship_info.focus_id
     *
     * @return the value of relationship_info.focus_id
     *
     * @mbggenerated Tue Jul 09 18:50:38 CST 2019
     */
    public Integer getFocusId() {
        return focusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relationship_info.focus_id
     *
     * @param focusId the value for relationship_info.focus_id
     *
     * @mbggenerated Tue Jul 09 18:50:38 CST 2019
     */
    public void setFocusId(Integer focusId) {
        this.focusId = focusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relationship_info.follow_user_id
     *
     * @return the value of relationship_info.follow_user_id
     *
     * @mbggenerated Tue Jul 09 18:50:38 CST 2019
     */
    public Integer getFollowUserId() {
        return followUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relationship_info.follow_user_id
     *
     * @param followUserId the value for relationship_info.follow_user_id
     *
     * @mbggenerated Tue Jul 09 18:50:38 CST 2019
     */
    public void setFollowUserId(Integer followUserId) {
        this.followUserId = followUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relationship_info.focus_user_id
     *
     * @return the value of relationship_info.focus_user_id
     *
     * @mbggenerated Tue Jul 09 18:50:38 CST 2019
     */
    public Integer getFocusUserId() {
        return focusUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relationship_info.focus_user_id
     *
     * @param focusUserId the value for relationship_info.focus_user_id
     *
     * @mbggenerated Tue Jul 09 18:50:38 CST 2019
     */
    public void setFocusUserId(Integer focusUserId) {
        this.focusUserId = focusUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relationship_info.operation_flag
     *
     * @return the value of relationship_info.operation_flag
     *
     * @mbggenerated Tue Jul 09 18:50:38 CST 2019
     */
    public Integer getOperationFlag() {
        return operationFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relationship_info.operation_flag
     *
     * @param operationFlag the value for relationship_info.operation_flag
     *
     * @mbggenerated Tue Jul 09 18:50:38 CST 2019
     */
    public void setOperationFlag(Integer operationFlag) {
        this.operationFlag = operationFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relationship_info.cancel_flag
     *
     * @return the value of relationship_info.cancel_flag
     *
     * @mbggenerated Tue Jul 09 18:50:38 CST 2019
     */
    public Integer getCancelFlag() {
        return cancelFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relationship_info.cancel_flag
     *
     * @param cancelFlag the value for relationship_info.cancel_flag
     *
     * @mbggenerated Tue Jul 09 18:50:38 CST 2019
     */
    public void setCancelFlag(Integer cancelFlag) {
        this.cancelFlag = cancelFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relationship_info.create_time
     *
     * @return the value of relationship_info.create_time
     *
     * @mbggenerated Tue Jul 09 18:50:38 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relationship_info.create_time
     *
     * @param createTime the value for relationship_info.create_time
     *
     * @mbggenerated Tue Jul 09 18:50:38 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relationship_info.modify_time
     *
     * @return the value of relationship_info.modify_time
     *
     * @mbggenerated Tue Jul 09 18:50:38 CST 2019
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relationship_info.modify_time
     *
     * @param modifyTime the value for relationship_info.modify_time
     *
     * @mbggenerated Tue Jul 09 18:50:38 CST 2019
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationship_info
     *
     * @mbggenerated Tue Jul 09 18:50:38 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RelationshipInfo other = (RelationshipInfo) that;
        return (this.getFocusId() == null ? other.getFocusId() == null : this.getFocusId().equals(other.getFocusId()))
            && (this.getFollowUserId() == null ? other.getFollowUserId() == null : this.getFollowUserId().equals(other.getFollowUserId()))
            && (this.getFocusUserId() == null ? other.getFocusUserId() == null : this.getFocusUserId().equals(other.getFocusUserId()))
            && (this.getOperationFlag() == null ? other.getOperationFlag() == null : this.getOperationFlag().equals(other.getOperationFlag()))
            && (this.getCancelFlag() == null ? other.getCancelFlag() == null : this.getCancelFlag().equals(other.getCancelFlag()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationship_info
     *
     * @mbggenerated Tue Jul 09 18:50:38 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFocusId() == null) ? 0 : getFocusId().hashCode());
        result = prime * result + ((getFollowUserId() == null) ? 0 : getFollowUserId().hashCode());
        result = prime * result + ((getFocusUserId() == null) ? 0 : getFocusUserId().hashCode());
        result = prime * result + ((getOperationFlag() == null) ? 0 : getOperationFlag().hashCode());
        result = prime * result + ((getCancelFlag() == null) ? 0 : getCancelFlag().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationship_info
     *
     * @mbggenerated Tue Jul 09 18:50:38 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", focusId=").append(focusId);
        sb.append(", followUserId=").append(followUserId);
        sb.append(", focusUserId=").append(focusUserId);
        sb.append(", operationFlag=").append(operationFlag);
        sb.append(", cancelFlag=").append(cancelFlag);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}