package com.ammy.shareme.server.dao.mapper;

import com.ammy.shareme.server.dao.model.CommentInfo;
import com.ammy.shareme.server.dao.model.CommentInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.context.annotation.Bean;
import org.springframework.stereotype.Component;

@Component
public interface CommentInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    int countByExample(CommentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    int deleteByExample(CommentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    int deleteByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    int insert(CommentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    int insertSelective(CommentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    List<CommentInfo> selectByExample(CommentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    CommentInfo selectByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    int updateByExampleSelective(@Param("record") CommentInfo record, @Param("example") CommentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    int updateByExample(@Param("record") CommentInfo record, @Param("example") CommentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    int updateByPrimaryKeySelective(CommentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    int updateByPrimaryKey(CommentInfo record);
}