package com.ammy.shareme.server.dao.mapper;

import com.ammy.shareme.server.dao.model.MomentInfo;
import com.ammy.shareme.server.dao.model.MomentInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface MomentInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moment_info
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    int countByExample(MomentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moment_info
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    int deleteByExample(MomentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moment_info
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    int deleteByPrimaryKey(Integer momentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moment_info
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    int insert(MomentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moment_info
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    int insertSelective(MomentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moment_info
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    List<MomentInfo> selectByExample(MomentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moment_info
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    MomentInfo selectByPrimaryKey(Integer momentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moment_info
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    int updateByExampleSelective(@Param("record") MomentInfo record, @Param("example") MomentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moment_info
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    int updateByExample(@Param("record") MomentInfo record, @Param("example") MomentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moment_info
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    int updateByPrimaryKeySelective(MomentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moment_info
     *
     * @mbggenerated Sat Jul 06 22:29:42 CST 2019
     */
    int updateByPrimaryKey(MomentInfo record);
}