package com.ammy.shareme.server.dao.mapper;

import com.ammy.shareme.server.dao.model.RelationshipInfo;
import com.ammy.shareme.server.dao.model.RelationshipInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RelationshipInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationship_info
     *
     * @mbggenerated Tue Jul 09 18:50:38 CST 2019
     */
    int countByExample(RelationshipInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationship_info
     *
     * @mbggenerated Tue Jul 09 18:50:38 CST 2019
     */
    int deleteByExample(RelationshipInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationship_info
     *
     * @mbggenerated Tue Jul 09 18:50:38 CST 2019
     */
    int deleteByPrimaryKey(Integer focusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationship_info
     *
     * @mbggenerated Tue Jul 09 18:50:38 CST 2019
     */
    int insert(RelationshipInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationship_info
     *
     * @mbggenerated Tue Jul 09 18:50:38 CST 2019
     */
    int insertSelective(RelationshipInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationship_info
     *
     * @mbggenerated Tue Jul 09 18:50:38 CST 2019
     */
    List<RelationshipInfo> selectByExample(RelationshipInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationship_info
     *
     * @mbggenerated Tue Jul 09 18:50:38 CST 2019
     */
    RelationshipInfo selectByPrimaryKey(Integer focusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationship_info
     *
     * @mbggenerated Tue Jul 09 18:50:38 CST 2019
     */
    int updateByExampleSelective(@Param("record") RelationshipInfo record, @Param("example") RelationshipInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationship_info
     *
     * @mbggenerated Tue Jul 09 18:50:38 CST 2019
     */
    int updateByExample(@Param("record") RelationshipInfo record, @Param("example") RelationshipInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationship_info
     *
     * @mbggenerated Tue Jul 09 18:50:38 CST 2019
     */
    int updateByPrimaryKeySelective(RelationshipInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationship_info
     *
     * @mbggenerated Tue Jul 09 18:50:38 CST 2019
     */
    int updateByPrimaryKey(RelationshipInfo record);
}